---
# Setup front-end load balancer tier


- name: setup load-balancer tier
  hosts: "{{ front_group }}"
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}
#    - {name: geerlingguy.haproxy, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: "{{ apps_group }}"
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier

- name: setup database tier
  hosts: "{{ appdbs }}"
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: geerlingguy.postgresql, tags: [dbs, postgres]}

# Check haproxy and tomcat working

      #- name: setup database tier
      # hosts: external
      # become: yes
      #roles:
      #- {name: checks, tags: checks}
