---
# This will enable a Windows service 

- name: enable a service
  win_service:
    service_name: "{{package_name}}"
    state: enabled
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
